' Developer Express Code Central Example:
' How to load a PDF document from the Stream
' 
' This example shows how to load a document from the Stream using the
' DocumentViewerControl.DocumentSource property.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T263193
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace LoadPDFDocument.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As LoadPDFDocument.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New LoadPDFDocument.Properties.Settings())), LoadPDFDocument.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return LoadPDFDocument.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
